/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOTAFATTOREX_H_RPCGEN
#define _VOTAFATTOREX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NUMGIUDICI 5

struct Giudice {
	char *nome;
	int punteggio;
};
typedef struct Giudice Giudice;

struct Output {
	Giudice giudici[NUMGIUDICI];
};
typedef struct Output Output;

struct Input {
	char *candidato;
	char operazione;
};
typedef struct Input Input;

#define VOTAFATTOREX 0x20000013
#define VOTAFATTOREXVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define classifica_giudici 1
extern  Output * classifica_giudici_1(void *, CLIENT *);
extern  Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define esprimi_voto 2
extern  void * esprimi_voto_1(Input *, CLIENT *);
extern  void * esprimi_voto_1_svc(Input *, struct svc_req *);
extern int votafattorex_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define classifica_giudici 1
extern  Output * classifica_giudici_1();
extern  Output * classifica_giudici_1_svc();
#define esprimi_voto 2
extern  void * esprimi_voto_1();
extern  void * esprimi_voto_1_svc();
extern int votafattorex_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Giudice (XDR *, Giudice*);
extern  bool_t xdr_Output (XDR *, Output*);
extern  bool_t xdr_Input (XDR *, Input*);

#else /* K&R C */
extern bool_t xdr_Giudice ();
extern bool_t xdr_Output ();
extern bool_t xdr_Input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VOTAFATTOREX_H_RPCGEN */
