/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "votafattorex.h"

bool_t
xdr_Giudice (XDR *xdrs, Giudice *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, 50))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->punteggio))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->giudici, NUMGIUDICI,
		sizeof (Giudice), (xdrproc_t) xdr_Giudice))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->candidato, 50))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->operazione))
		 return FALSE;
	return TRUE;
}
